# Generated by Django 5.1.4 on 2024-12-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_category_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_img',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Изображение'),
        ),
    ]
